### ISSUE TITLE
Using "Add to rate later" does not open a new window

### ISSUE THREAD

**Issue by lenhoanglnh** [tournesol-app/tournesol-chrome-extension#6]
Just display a message saying "the video has been successfully added", just like Pocket does (without the ad 😅), and maybe with a link to the rate page, in case the user wants to rate the video directly.
<img width="1195" alt="Screen Shot 2021-03-23 at 19 25 12" src="https://user-images.githubusercontent.com/10453308/112198545-804e2300-8c0d-11eb-876e-33884038b01a.png">

**Comment by lfaucon** [comment]
UPDATE:


Getting the cookie
```
withCookie = (callback) => {
  chrome.cookies.get(
    { url: 'https://tournesol.app/', name: 'csrftoken' },
    (cookie) => callback(cookie.value),
  );
};
```


Doing the API request:
```
addRateLater = (csrftoken) => {
  console.log('with referer');
  console.log(csrftoken);
  fetch('https://tournesol.app/api/v2/rate_later/', {
    credentials: 'include',
    method: 'POST',
    mode: 'cors',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      'X-CSRFToken': csrftoken,
    },
    body: JSON.stringify({ video: 'gW0JQ1OoLwM' }),
  })
    .then(function (response) {
      console.log(response);
      return response.json();
    })
    .then(console.log)
    .catch(function (ex) {
      console.log('Request failed', ex);
    });
};
```

This code doesn't work as is. Could be part of menu.js or background.js. It also require adding tournesol url in the permissions in manifest.json

**Comment by lfaucon** [comment]
Done.
