### ISSUE TITLE
Alert showing on wrong screen with dual-screen

### ISSUE THREAD

**Issue by mbourand** [tournesol-app/tournesol-chrome-extension#7]
## General informations
When clicking on a incorrect element (like a channel). I noticed that the alert appeared on my main screen, while chrome was opened on the second one.

## Steps to reproduce
1. Close every instance of chrome currently opened
2. Open Chrome on a second screen
3. Go to https://www.youtube.com/
4. Right click on a channel icon
5. Click on "Rate later on Tournesol"

## Example
![issue_tournesol](https://user-images.githubusercontent.com/54736052/115307524-9f3ac900-a169-11eb-8ad5-80b6a1d75ad6.png)

**Comment by lfaucon** [comment]
I think recent changes removed this issue. Re-open if it resurfaces after v1.6
